model:
  encoder: resnet18
  skip_ch: 16
  aux_losses: -1
  pretrained: True

data:
  type: voc2012_aug
  num_classes: 21
  num_workers: 4
  batch_size: 16
  max_training_samples: 1000
  
train:
  seed: 42
  epochs: 20
  lr: 0.0004
  weight_decay: 0.0001
  optimizer: adamw
  accum_steps: 2
  device: cuda
  loss_type: focal
  save_name: 'test_resnet18_voc_focal'

  logger:
    use_tensorboard: True
    log_dir: ./runs