model:
  encoder: resnet18
  skip_ch: 16
  aux_losses: -1
  pretrained: True

data:
  type: voc2012_aug
  num_classes: 21
  num_workers: 2
  batch_size: 1
  max_training_samples: 10
  
train:
  seed: 42
  num_epochs: 20
  lr: 0.001
  weight_decay: 0.0001
  optimizer: adamw
  accum_steps: 2
  resume: ''
  device: cpu
  loss_type: focal

  logger:
    use_tensorboard: False
    use_wandb: False
    log_dir: ./logs/