model:
  encoder: resnet18
  skip_ch: 64
  aux_losses: 2
  pretrained: True

data:
  type: voc2012_aug
  num_classes: 21
  num_workers: 0
  batch_size: 16
  max_training_samples: -1
  
train:
  seed: 42
  epochs: 20
  lr: 0.001
  weight_decay: 0.0001
  optimizer: adamw
  accum_steps: 4
  resume: ''
  save_dir: ./checkpoints/
  save_name: u3p_resnet34_voc
  loss_type: focal
  warmup_iters: 1

  logger:
    use_tensorboard: True
    log_dir: ./logs


  
